### ISSUE TITLE
Rename all instances of Duke (Project Name) as DIYeats

### ISSUE THREAD

**Issue by HashirZahir** [AY1920S1-CS2113T-W13-4/main#203]
Even the jar file released must be called DIYeats. Otherwise prof said it is a bug.

**Comment by Fractalisk** [comment]
Duke package renamed to diyeats, and DukeException renamed to ProgramException

**Comment by Fractalisk** [comment]
Some comments still include duke, require cleanup

**Comment by HashirZahir** [comment]
The only significant place where I could find duke was `src/test/java/diyeats/functions/FunctionTest.java`. Rest of the instances of `duke` are in unused code. Is this issue resolved then?
